# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mac/Downloads/DSAI-AI-Project-main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mac/Downloads/DSAI-AI-Project-main

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all:
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mac/Downloads/DSAI-AI-Project-main/CMakeFiles /Users/mac/Downloads/DSAI-AI-Project-main//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mac/Downloads/DSAI-AI-Project-main/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

#=============================================================================
# Target rules for targets named Chess

# Build rule for target.
Chess:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Chess
.PHONY : Chess

# fast build rule for target.
Chess/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/build
.PHONY : Chess/fast

res/appIcon/winAppIcon.o: res/appIcon/winAppIcon.cpp.o
.PHONY : res/appIcon/winAppIcon.o

# target to build an object file
res/appIcon/winAppIcon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/res/appIcon/winAppIcon.cpp.o
.PHONY : res/appIcon/winAppIcon.cpp.o

res/appIcon/winAppIcon.i: res/appIcon/winAppIcon.cpp.i
.PHONY : res/appIcon/winAppIcon.i

# target to preprocess a source file
res/appIcon/winAppIcon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/res/appIcon/winAppIcon.cpp.i
.PHONY : res/appIcon/winAppIcon.cpp.i

res/appIcon/winAppIcon.s: res/appIcon/winAppIcon.cpp.s
.PHONY : res/appIcon/winAppIcon.s

# target to generate assembly for a file
res/appIcon/winAppIcon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/res/appIcon/winAppIcon.cpp.s
.PHONY : res/appIcon/winAppIcon.cpp.s

src/BBBasedMovement.o: src/BBBasedMovement.cpp.o
.PHONY : src/BBBasedMovement.o

# target to build an object file
src/BBBasedMovement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/BBBasedMovement.cpp.o
.PHONY : src/BBBasedMovement.cpp.o

src/BBBasedMovement.i: src/BBBasedMovement.cpp.i
.PHONY : src/BBBasedMovement.i

# target to preprocess a source file
src/BBBasedMovement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/BBBasedMovement.cpp.i
.PHONY : src/BBBasedMovement.cpp.i

src/BBBasedMovement.s: src/BBBasedMovement.cpp.s
.PHONY : src/BBBasedMovement.s

# target to generate assembly for a file
src/BBBasedMovement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/BBBasedMovement.cpp.s
.PHONY : src/BBBasedMovement.cpp.s

src/BBKingCheckLogic.o: src/BBKingCheckLogic.cpp.o
.PHONY : src/BBKingCheckLogic.o

# target to build an object file
src/BBKingCheckLogic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/BBKingCheckLogic.cpp.o
.PHONY : src/BBKingCheckLogic.cpp.o

src/BBKingCheckLogic.i: src/BBKingCheckLogic.cpp.i
.PHONY : src/BBKingCheckLogic.i

# target to preprocess a source file
src/BBKingCheckLogic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/BBKingCheckLogic.cpp.i
.PHONY : src/BBKingCheckLogic.cpp.i

src/BBKingCheckLogic.s: src/BBKingCheckLogic.cpp.s
.PHONY : src/BBKingCheckLogic.s

# target to generate assembly for a file
src/BBKingCheckLogic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/BBKingCheckLogic.cpp.s
.PHONY : src/BBKingCheckLogic.cpp.s

src/ChessBoard.o: src/ChessBoard.cpp.o
.PHONY : src/ChessBoard.o

# target to build an object file
src/ChessBoard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/ChessBoard.cpp.o
.PHONY : src/ChessBoard.cpp.o

src/ChessBoard.i: src/ChessBoard.cpp.i
.PHONY : src/ChessBoard.i

# target to preprocess a source file
src/ChessBoard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/ChessBoard.cpp.i
.PHONY : src/ChessBoard.cpp.i

src/ChessBoard.s: src/ChessBoard.cpp.s
.PHONY : src/ChessBoard.s

# target to generate assembly for a file
src/ChessBoard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/ChessBoard.cpp.s
.PHONY : src/ChessBoard.cpp.s

src/DSAI-AI-Project.o: src/DSAI-AI-Project.cpp.o
.PHONY : src/DSAI-AI-Project.o

# target to build an object file
src/DSAI-AI-Project.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/DSAI-AI-Project.cpp.o
.PHONY : src/DSAI-AI-Project.cpp.o

src/DSAI-AI-Project.i: src/DSAI-AI-Project.cpp.i
.PHONY : src/DSAI-AI-Project.i

# target to preprocess a source file
src/DSAI-AI-Project.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/DSAI-AI-Project.cpp.i
.PHONY : src/DSAI-AI-Project.cpp.i

src/DSAI-AI-Project.s: src/DSAI-AI-Project.cpp.s
.PHONY : src/DSAI-AI-Project.s

# target to generate assembly for a file
src/DSAI-AI-Project.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/DSAI-AI-Project.cpp.s
.PHONY : src/DSAI-AI-Project.cpp.s

src/ToolBar.o: src/ToolBar.cpp.o
.PHONY : src/ToolBar.o

# target to build an object file
src/ToolBar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/ToolBar.cpp.o
.PHONY : src/ToolBar.cpp.o

src/ToolBar.i: src/ToolBar.cpp.i
.PHONY : src/ToolBar.i

# target to preprocess a source file
src/ToolBar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/ToolBar.cpp.i
.PHONY : src/ToolBar.cpp.i

src/ToolBar.s: src/ToolBar.cpp.s
.PHONY : src/ToolBar.s

# target to generate assembly for a file
src/ToolBar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/ToolBar.cpp.s
.PHONY : src/ToolBar.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Chess"
	@echo "... res/appIcon/winAppIcon.o"
	@echo "... res/appIcon/winAppIcon.i"
	@echo "... res/appIcon/winAppIcon.s"
	@echo "... src/BBBasedMovement.o"
	@echo "... src/BBBasedMovement.i"
	@echo "... src/BBBasedMovement.s"
	@echo "... src/BBKingCheckLogic.o"
	@echo "... src/BBKingCheckLogic.i"
	@echo "... src/BBKingCheckLogic.s"
	@echo "... src/ChessBoard.o"
	@echo "... src/ChessBoard.i"
	@echo "... src/ChessBoard.s"
	@echo "... src/DSAI-AI-Project.o"
	@echo "... src/DSAI-AI-Project.i"
	@echo "... src/DSAI-AI-Project.s"
	@echo "... src/ToolBar.o"
	@echo "... src/ToolBar.i"
	@echo "... src/ToolBar.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

